cartDAO=com.DAOImpl.CartDAOImpl
orderDAO=com.DAOImpl.OrderDAOImpl
paymentDAO=com.DAOImpl.PaymentDAOImpl
productDAO=com.DAOImpl.ProductDAOImpl
userDAO=com.DAOImpl.UserDAOImpl

cartService=com.serviceimpl.CartServiceImpl
orderService=com.serviceimpl.OrderServiceImpl
paymentService=com.serviceimpl.PaymentServiceImpl
productService=com.serviceimpl.ProductServiceImpl
userService=com.serviceimpl.UserServiceImpl